packages:
  - "apps/*"
  - "packages/*"

catalog:
  "tamagui": "^1.135.7"
  "@tamagui/animations-react-native": "^1.135.7"
  "@tamagui/babel-plugin": "^1.135.7"
  "@tamagui/card": "^1.135.7"
  "@tamagui/config": "^1.135.7"
  "@tamagui/core": "^1.135.7"
  "@tamagui/font-inter": "^1.135.7"
  "@tamagui/lucide-icons": "^1.135.7"
  "@tamagui/next-plugin": "^1.135.7"
  "@tamagui/next-theme": "^1.135.7"
  "@tamagui/polyfill-dev": "^1.135.7"
  "@tamagui/shorthands": "^1.135.7"
  "@tamagui/themes": "^1.135.7"
  "@tamagui/toast": "^1.135.7"
