import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { TamaguiProvider } from 'tamagui'
import { config, Button, Text } from '@buttergolf/ui'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import Tamagui CSS (will be generated in production)
if (process.env.NODE_ENV === 'production') {
  require('../../public/tamagui.css')
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style
          dangerouslySetInnerHTML={{
            __html: config.getCSS({
              exclude: process.env.NODE_ENV === 'production' ? 'design-system' : null,
            }),
          }}
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TamaguiProvider config={config} defaultTheme="light">
          <div style={{ padding: 12 }}>
            <Text>Hello from web (Tamagui)</Text>
            <Button onPress={() => alert('Tamagui button clicked')}>Click me</Button>
          </div>
          {children}
        </TamaguiProvider>
      </body>
    </html>
  );
}
