/**
 * @deprecated This re-export shim is deprecated and will be removed in a future release.
 * 
 * MIGRATION NOTICE:
 * Please import directly from @buttergolf/config instead:
 * 
 *   Before: import { config } from "@buttergolf/ui"
 *   After:  import { config } from "@buttergolf/config"
 * 
 * The source of truth for Tamagui configuration lives in:
 *   packages/config/src/tamagui.config.ts
 * 
 * This file exists only for backward compatibility and will be removed after
 * all consumers have migrated to the new import path.
 */

// Emit a development-time warning to help developers migrate (only once per session)
if (process.env.NODE_ENV === 'development') {
  // Use a global flag to prevent multiple warnings
  const globalKey = '__TAMAGUI_CONFIG_DEPRECATION_WARNING_SHOWN__';
  if (!(globalThis as any)[globalKey]) {
    (globalThis as any)[globalKey] = true;
    console.warn(
      '[DEPRECATION WARNING] Importing Tamagui config from "@buttergolf/ui" is deprecated.\n' +
      'Please update your imports to use "@buttergolf/config" instead.\n' +
      'See packages/config/src/tamagui.config.ts for the source of truth.'
    );
  }
}

// DEPRECATED: Do not edit this file.
// The Tamagui config source of truth lives in `packages/config/src/tamagui.config.ts`.
// This file exists only as a thin re-export for backward compatibility.
export { config } from '@buttergolf/config'
export type { AppConfig } from '@buttergolf/config'
export { config as default } from '@buttergolf/config'
