// DEPRECATED: Do not edit this file.
// The Tamagui config source of truth lives in `packages/config/src/tamagui.config.ts`.
// This file exists only as a thin re-export for backward compatibility.
export { config } from '@buttergolf/config'
export type { AppConfig } from '@buttergolf/config'
export { config as default } from '@buttergolf/config'
