"use client";

import React, { useEffect, useMemo, useState } from "react";
import { TextInput, Keyboard } from "react-native";
import {
  Column,
  Row,
  Text,
  View,
  Input,
  ScrollView,
} from "@buttergolf/ui";
import {
  Sparkles,
  Type,
  FileText,
  PoundSterling,
} from "@tamagui/lucide-icons";

import type { SellFormData } from "../types";
import { CONDITION_OPTIONS } from "../types";

interface ListingStepProps {
  formData: SellFormData;
  onUpdate: (updates: Partial<SellFormData>) => void;
  direction: "forward" | "backward";
}

// Helper to singularize category name
function singularize(word: string): string {
  if (word.endsWith("ies")) {
    return word.slice(0, -3) + "y";
  }
  if (word.endsWith("s") && !word.endsWith("ss")) {
    return word.slice(0, -1);
  }
  return word;
}

export function ListingStep({
  formData,
  onUpdate,
  direction,
}: Readonly<ListingStepProps>) {
  const [titleFocused, setTitleFocused] = useState(false);
  const [descFocused, setDescFocused] = useState(false);
  const [priceFocused, setPriceFocused] = useState(false);

  // Auto-generate title from brand, model, category, condition
  const autoGeneratedTitle = useMemo(() => {
    const parts: string[] = [];

    if (formData.brandName) {
      parts.push(formData.brandName);
    }
    if (formData.modelName) {
      parts.push(formData.modelName);
    }
    if (formData.categoryName) {
      parts.push(singularize(formData.categoryName));
    }
    if (formData.condition) {
      const conditionLabel = CONDITION_OPTIONS.find(
        (c) => c.value === formData.condition
      )?.label;
      if (conditionLabel && conditionLabel !== "New") {
        parts.push(`(${conditionLabel})`);
      }
    }

    return parts.join(" ");
  }, [
    formData.brandName,
    formData.modelName,
    formData.categoryName,
    formData.condition,
  ]);

  // Update title when auto-generated title changes (if title is empty or matches previous auto-generated)
  useEffect(() => {
    if (!formData.title || formData.title === autoGeneratedTitle) {
      onUpdate({ title: autoGeneratedTitle });
    }
  }, [autoGeneratedTitle, onUpdate]);

  const handlePriceChange = (text: string) => {
    // Only allow numbers and one decimal point
    const cleaned = text.replaceAll(/[^0-9.]/g, "");
    const parts = cleaned.split(".");
    if (parts.length > 2) {
      return;
    }
    if (parts[1] && parts[1].length > 2) {
      return;
    }
    onUpdate({ price: cleaned });
  };

  const descriptionLength = formData.description.length;
  const maxDescLength = 1000;

  return (
    <Column
      flex={1}
      animation="quick"
      enterStyle={{
        opacity: 0,
        x: direction === "forward" ? 50 : -50,
      }}
      exitStyle={{
        opacity: 0,
        x: direction === "forward" ? -50 : 50,
      }}
    >
      <ScrollView
        flex={1}
        contentContainerStyle={{
          padding: 20,
        }}
        keyboardShouldPersistTaps="handled"
        onScrollBeginDrag={() => Keyboard.dismiss()}
      >
        {/* Header Section */}
        <Column gap="$2" marginBottom="$6">
          <Text
            fontFamily="$heading"
            size="$10"
            fontWeight="800"
            color="$ironstone"
          >
            Create your listing
          </Text>
          <Text size="$5" fontWeight="400" color="$slateSmoke">
            Write a compelling title and description to attract buyers
          </Text>
        </Column>

        {/* Form Fields */}
        <Column gap="$5">
          {/* Title */}
          <Column gap="$2">
            <Row alignItems="center" gap="$1">
              <Text size="$4" fontWeight="600" color="$ironstone">
                Title
              </Text>
              <Text size="$4" fontWeight="600" color="$error">
                *
              </Text>
            </Row>
            <Row
              backgroundColor="$pureWhite"
              borderWidth={2}
              borderColor={titleFocused ? "$spicedClementine" : "$cloudMist"}
              borderRadius="$xl"
              paddingHorizontal="$4"
              paddingVertical="$3"
              alignItems="center"
              gap="$3"
            >
              <Type size={20} color="$slateSmoke" />
              <Input
                flex={1}
                value={formData.title}
                onChangeText={(text) => onUpdate({ title: text })}
                onFocus={() => setTitleFocused(true)}
                onBlur={() => setTitleFocused(false)}
                placeholder="Enter a title for your listing"
                placeholderTextColor="$slateSmoke"
                borderWidth={0}
                backgroundColor="transparent"
                size="$6"
                color="$ironstone"
              />
            </Row>
            <Row
              alignItems="center"
              gap="$2"
              backgroundColor="$lemonHaze"
              paddingHorizontal="$3"
              paddingVertical="$2"
              borderRadius="$lg"
            >
              <Sparkles size={14} color="$burntOlive" />
              <Text size="$2" fontWeight="500" color="$burntOlive">
                Auto-generated from your item details
              </Text>
            </Row>
          </Column>

          {/* Description */}
          <Column gap="$2">
            <Text size="$4" fontWeight="600" color="$ironstone">
              Description
            </Text>
            <Column
              backgroundColor="$pureWhite"
              borderWidth={2}
              borderColor={descFocused ? "$spicedClementine" : "$cloudMist"}
              borderRadius="$xl"
              overflow="hidden"
            >
              <Row paddingHorizontal="$4" paddingTop="$3" gap="$3">
                <FileText
                  size={20}
                  color="$slateSmoke"
                  style={{ marginTop: 2 }}
                />
                <View flex={1}>
                  <TextInput
                    value={formData.description}
                    onChangeText={(text) => {
                      if (text.length <= maxDescLength) {
                        onUpdate({ description: text });
                      }
                    }}
                    onFocus={() => setDescFocused(true)}
                    onBlur={() => setDescFocused(false)}
                    placeholder="Describe your item - condition details, why you're selling, what's included..."
                    placeholderTextColor="#545454"
                    multiline
                    numberOfLines={5}
                    textAlignVertical="top"
                    style={{
                      fontSize: 16,
                      color: "#323232",
                      minHeight: 120,
                      fontFamily: "Urbanist-Regular",
                    }}
                  />
                </View>
              </Row>
              <Row
                justifyContent="flex-end"
                paddingHorizontal="$4"
                paddingBottom="$3"
              >
                <Text
                  size="$2"
                  fontWeight="500"
                  color={descriptionLength > maxDescLength * 0.9 ? "$error" : "$slateSmoke"}
                >
                  {descriptionLength}/{maxDescLength}
                </Text>
              </Row>
            </Column>
          </Column>

          {/* Price */}
          <Column gap="$2">
            <Row alignItems="center" gap="$1">
              <Text size="$4" fontWeight="600" color="$ironstone">
                Price
              </Text>
              <Text size="$4" fontWeight="600" color="$error">
                *
              </Text>
            </Row>
            <Row
              backgroundColor="$pureWhite"
              borderWidth={2}
              borderColor={priceFocused ? "$spicedClementine" : "$cloudMist"}
              borderRadius="$xl"
              alignItems="center"
              overflow="hidden"
            >
              <View
                backgroundColor="$gray100"
                paddingHorizontal="$4"
                paddingVertical="$4"
                borderRightWidth={1}
                borderRightColor="$cloudMist"
              >
                <PoundSterling size={20} color="$ironstone" />
              </View>
              <Input
                flex={1}
                value={formData.price}
                onChangeText={handlePriceChange}
                onFocus={() => setPriceFocused(true)}
                onBlur={() => setPriceFocused(false)}
                placeholder="0.00"
                placeholderTextColor="$slateSmoke"
                keyboardType="decimal-pad"
                borderWidth={0}
                backgroundColor="transparent"
                paddingHorizontal="$4"
                paddingVertical="$4"
                size="$8"
                fontWeight="600"
                color="$ironstone"
              />
            </Row>
            <Text size="$3" color="$slateSmoke">
              💡 Set a competitive price - check similar listings for guidance
            </Text>
          </Column>
        </Column>

        {/* Pricing Tips */}
        <Column
          marginTop="$6"
          backgroundColor="$gray100"
          borderRadius="$xl"
          padding="$4"
          gap="$3"
        >
          <Text
            fontFamily="$heading"
            size="$5"
            fontWeight="700"
            color="$ironstone"
          >
            Pricing tips
          </Text>
          <Column gap="$2">
            <Row alignItems="flex-start" gap="$2">
              <Text size="$4" color="$slateSmoke">
                •
              </Text>
              <Text size="$4" color="$slateSmoke" flex={1}>
                Research similar items to price competitively
              </Text>
            </Row>
            <Row alignItems="flex-start" gap="$2">
              <Text size="$4" color="$slateSmoke">
                •
              </Text>
              <Text size="$4" color="$slateSmoke" flex={1}>
                Consider the condition and original retail price
              </Text>
            </Row>
            <Row alignItems="flex-start" gap="$2">
              <Text size="$4" color="$slateSmoke">
                •
              </Text>
              <Text size="$4" color="$slateSmoke" flex={1}>
                Items priced fairly sell 3x faster
              </Text>
            </Row>
          </Column>
        </Column>
      </ScrollView>
    </Column>
  );
}
