"use client";

import React, { useEffect, useMemo } from "react";
import { TextInput } from "react-native";
import {
  Column,
  Row,
  Text,
  Heading,
  View,
  Input,
  ScrollView,
} from "@buttergolf/ui";
import { Info } from "@tamagui/lucide-icons";

import type { SellFormData } from "../types";
import { CONDITION_OPTIONS } from "../types";

interface ListingStepProps {
  formData: SellFormData;
  onUpdate: (updates: Partial<SellFormData>) => void;
  direction: "forward" | "backward";
}

// Helper to singularize category name
function singularize(word: string): string {
  if (word.endsWith("ies")) {
    return word.slice(0, -3) + "y";
  }
  if (word.endsWith("s") && !word.endsWith("ss")) {
    return word.slice(0, -1);
  }
  return word;
}

export function ListingStep({
  formData,
  onUpdate,
  direction,
}: Readonly<ListingStepProps>) {
  // Auto-generate title from brand, model, category, condition
  const autoGeneratedTitle = useMemo(() => {
    const parts: string[] = [];

    if (formData.brandName) {
      parts.push(formData.brandName);
    }
    if (formData.modelName) {
      parts.push(formData.modelName);
    }
    if (formData.categoryName) {
      parts.push(singularize(formData.categoryName));
    }
    if (formData.condition) {
      const conditionLabel = CONDITION_OPTIONS.find(
        (c) => c.value === formData.condition
      )?.label;
      if (conditionLabel && conditionLabel !== "New") {
        parts.push(`(${conditionLabel})`);
      }
    }

    return parts.join(" ");
  }, [
    formData.brandName,
    formData.modelName,
    formData.categoryName,
    formData.condition,
  ]);

  // Update title when auto-generated title changes (if title is empty or matches previous auto-generated)
  useEffect(() => {
    if (!formData.title || formData.title === autoGeneratedTitle) {
      onUpdate({ title: autoGeneratedTitle });
    }
    // Note: formData.title is intentionally omitted to prevent infinite loops
    // when the title is auto-updated. onUpdate is stable (useCallback with []).
  }, [autoGeneratedTitle, onUpdate]);

  const handlePriceChange = (text: string) => {
    // Only allow numbers and one decimal point
    const cleaned = text.replaceAll(/[^0-9.]/g, "");
    const parts = cleaned.split(".");
    if (parts.length > 2) {
      return;
    }
    if (parts[1] && parts[1].length > 2) {
      return;
    }
    onUpdate({ price: cleaned });
  };

  return (
    <Column
      flex={1}
      animation="quick"
      enterStyle={{
        opacity: 0,
        x: direction === "forward" ? 50 : -50,
      }}
      exitStyle={{
        opacity: 0,
        x: direction === "forward" ? -50 : 50,
      }}
    >
      <ScrollView
        flex={1}
        contentContainerStyle={{
          padding: 16,
        }}
        keyboardShouldPersistTaps="handled"
      >
        {/* Instructions */}
        <Column gap="$2" marginBottom="$4">
          <Heading level={4} fontSize={16} color="$text" fontWeight="600">
            Listing information
          </Heading>
          <Text fontSize={14} color="$textSecondary">
            Add a title, description, and set your price
          </Text>
        </Column>

        {/* Form Fields */}
        <Column gap="$4">
          {/* Title */}
          <Column gap="$1">
            <Text fontSize={14} fontWeight="500" color="$text">
              Title <Text color="$error">*</Text>
            </Text>
            <Input
              value={formData.title}
              onChangeText={(text) => onUpdate({ title: text })}
              placeholder="Enter a title for your listing"
              placeholderTextColor="$textMuted"
              backgroundColor="$surface"
              borderWidth={1}
              borderColor="$border"
              borderRadius="$lg"
              paddingHorizontal="$3"
              paddingVertical="$3"
              fontSize={15}
            />
            <Row alignItems="center" gap="$1" marginTop="$1">
              <Info size={12} color="$textSecondary" />
              <Text fontSize={12} color="$textSecondary">
                Auto-generated from your item details. Edit if needed.
              </Text>
            </Row>
          </Column>

          {/* Description */}
          <Column gap="$1">
            <Text fontSize={14} fontWeight="500" color="$text">
              Description
            </Text>
            <View
              backgroundColor="$surface"
              borderWidth={1}
              borderColor="$border"
              borderRadius="$lg"
              padding="$3"
              minHeight={120}
            >
              <TextInput
                value={formData.description}
                onChangeText={(text) => onUpdate({ description: text })}
                placeholder="Describe your item - condition details, why you're selling, etc."
                placeholderTextColor="#888"
                multiline
                numberOfLines={5}
                textAlignVertical="top"
                style={{
                  fontSize: 15,
                  color: "#323232",
                  minHeight: 100,
                }}
              />
            </View>
            <Text fontSize={12} color="$textSecondary" marginTop="$1">
              {formData.description.length}/1000 characters
            </Text>
          </Column>

          {/* Price */}
          <Column gap="$1">
            <Text fontSize={14} fontWeight="500" color="$text">
              Price <Text color="$error">*</Text>
            </Text>
            <Row
              backgroundColor="$surface"
              borderWidth={1}
              borderColor="$border"
              borderRadius="$lg"
              alignItems="center"
              overflow="hidden"
            >
              <View
                backgroundColor="$cloudMist"
                paddingHorizontal="$3"
                paddingVertical="$3"
                borderRightWidth={1}
                borderRightColor="$border"
              >
                <Text fontSize={16} fontWeight="600" color="$text">
                  £
                </Text>
              </View>
              <Input
                flex={1}
                value={formData.price}
                onChangeText={handlePriceChange}
                placeholder="0.00"
                placeholderTextColor="$textMuted"
                keyboardType="decimal-pad"
                borderWidth={0}
                backgroundColor="transparent"
                paddingHorizontal="$3"
                paddingVertical="$3"
                fontSize={16}
              />
            </Row>
            <Text fontSize={12} color="$textSecondary" marginTop="$1">
              Set a competitive price to attract buyers
            </Text>
          </Column>
        </Column>
      </ScrollView>
    </Column>
  );
}
